// ui-spec.js
// Centralized UI configuration for window dimensions and styles
export default {
  home: {
    window: { width: 800, height: 600, stroke: 4, bg: '#FFFBE3', radius: 10, overflowHidden: true },
    titleBar: { height: 60, padding: [0, 30, 0, 30], bg: '#FFD992' },
    titleText: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    contentArea: { height: 540, padding: [80, 0, 20, 0], bg: '#FFFBE3' },
    mainText: { fontSize: '5rem', fontWeight: 'bold', colors: ['#333333', '#32117C'], marginLeft: 0 },
    supportingText: { fontSize: '2rem', fontWeight: 'bold', color: '#333333', marginTop: 20, marginBottom: 100},
    iconGroup: { 
      about: { width: 100, height: 140, margin: 10, source: "/sources/ico/home/about.png" },
      work: { width: 100, height: 140, margin: 10, source: "/sources/ico/home/work.png" },
      links: { width: 100, height: 140, margin: 10, source: "/sources/ico/home/links.png" },
      faq: { width: 100, height: 140, margin: 10, source: "/sources/ico/home/faq.png" },
      museum: { width: 100, height: 140, margin: 10, source: "/sources/ico/home/museum.png" },
    },
    icon: { width: 100, height: 100 },
    iconText: { width: 100, height: 40, fontSize: '1.25rem', fontWeight: 'bold', color: '#333333' },
  },
  about: {
    window: { width: 800, height: 600, stroke: 4, bg: '#FFFBE3', radius: 10, overflowHidden: true },
    titleBar: { height: 60, padding: [0, 30, 0, 30], bg: '#FFD992' },
    titleText: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    closeButton: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    contentArea: { height: 540, padding: [20, 0, 0, 40] },
    avatar: { width: 150, height: 150, radius: 75, margin: [20, 20, 20, 60], source: "/sources/img/about/cn_mel.jpeg" },
    nameText: { fontSize: '2rem', fontWeight: 'bold', color: '#32117C', margin: [50, 0, 0, 20] },
    quoteText: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333', margin: [0, 0, 0, 20] },
    separator: { offsetLeft: -40, width: 800, borderWidth: 0.5, color: '#979797', opacity: 0.25, margin: [10, 0, 15, 0] },
    content: { 
      normalText: { fontSize: '1rem', color: '#333333', marginLeft: 40},
      heading1: { fontSize: '2rem', color: '#333333' },
    },
  },
  work: {
    window: { width: 1000, height: 600, stroke: 4, bg: '#FFFBE3', radius: 10, overflowHidden: true },
    titleBar: { height: 60, padding: [0, 30, 0, 30], bg: '#FFD992' },
    titleText: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    closeButton: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    contentArea: { height: 540, padding: [20, 40, 0, 40] },
    section1: {
      title: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333', margin: [0, 0, 0, 0] },
      content: { padding: [20, 20, 40, 20] },
      spacing: { marginBottom: 20 },
    },
    section2: {
      title: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333', margin: [0, 0, 0, 0] },
      content: { padding: [20, 20, 40, 20] },
      spacing: { marginBottom: 20 },
      videoSlot: { 
        backgroundColor: '#DBDBDB', 
        borderRadius: 5,
        fontSize: '1rem',
        color: '#333333',
      },
      videoGrid: { gap: 20 },
      videoSlots: {
        slot1: { width: 430, height: 242, showDimensions: false, source: "https://youtu.be/TdlOwJ3p9Bw" },  // horizontal 16:9
        slot2: { width: 430, height: 242, showDimensions: false, source: "https://youtu.be/5c-9aJYq-XA" }, // horizontal 16:9
        slot3: { width: 253, height: 450, showDimensions: false, source: "https://youtube.com/shorts/sSbO3aEqthw?feature=share" }, // vertical 9:16
        slot4: { width: 338, height: 450, showDimensions: false, source: "https://youtube.com/shorts/yDfvRPXB32o?feature=share" },  // vertical 3:4
        slot5: { width: 253, height: 450, showDimensions: false, source: "https://youtube.com/shorts/TUk7U1mkRu0?feature=share" },  // vertical 9:16
      },
      videoSettings: {
        autoplay: false,
        muted: true,
        loop: false,
        controls: false,
        preload: 'metadata',
        objectFit: 'cover' // or 'contain', 'fill',
      }
    },
    section3: {
      title: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333', margin: [0, 0, 0, 0] },
      content: { padding: [20, 20, 40, 20] },
      developmentText: { margin: 0, paddingLeft: 20},
      githubLink: { marginTop: 10, fontSize: '1rem', color: '#333333' },
    }
  },
  links: {
    window: { width: 600, height: 400, stroke: 4, bg: '#FFFBE3', radius: 10, overflowHidden: true },
    titleBar: { height: 60, padding: [0, 30, 0, 30], bg: '#FFD992' },
    titleText: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    closeButton: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    contentArea: { height: 340, padding: [15, 15, 0, 15] },  
    iconGroup: {
      group1: { width: 100, height: 120, margin: [0, 20, 10, 20], source: "/sources/ico/links/discord.png" },
      group2: { width: 100, height: 120, margin: [0, 20, 10, 20], source: "/sources/ico/links/instagram.png" },
      group3: { width: 100, height: 120, margin: [0, 20, 10, 20], source: "/sources/ico/links/telegram.png" },
      group4: { width: 100, height: 120, margin: [0, 20, 10, 20], source: "/sources/ico/links/linkedin.png" },
      group5: { width: 100, height: 120, margin: [0, 20, 10, 20], source: "/sources/ico/links/github.png" },
      group6: { width: 100, height: 120, margin: [0, 20, 10, 20], source: "/sources/ico/links/x.png" },
      group7: { width: 100, height: 120, margin: [0, 20, 10, 20], source: "/sources/ico/links/whatsapp.png" },
      group8: { width: 100, height: 120, margin: [0, 20, 10, 20], source: "/sources/ico/links/youtube.png" },
    },
    icons: { width: 80, height: 80 },
    iconText: { width: 100, height: 40, fontSize: '1.25rem', fontWeight: 'bold', color: '#333333' },
    descriptionFrame: { width: 540, height: 40, radius: 5, bg: '#FFFFFF', stroke: 2, strokeColor: '#333333' },
    description: { fontSize: '1rem', color: '#333333' },
  },
  contact: {
    window: { width: 600, height: 600, stroke: 4, bg: '#FFFBE3', radius: 10, overflowHidden: true },
    titleBar: { height: 60, padding: [0, 30, 0, 30], bg: '#FFD992' },
    titleText: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    closeButton: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    contentArea: { height: 540, padding: [15, 20, 0, 20] },
    emailTitle: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333'},
    character: {},
    descriptionText: {},
    mailText: {},
    mailingFrame: {},
    mailingButton: {},
  },
  faq: {
    window: { width: 600, height: 600, stroke: 4, bg: '#FFFBE3', radius: 10, overflowHidden: true },
    titleBar: { height: 60, padding: [0, 30, 0, 30], bg: '#FFD992' },
    titleText: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    closeButton: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    contentArea: { height: 540, padding: [20, 0, 0, 20] },
    scrollContainer: { height: 'calc(100% - 40px)', overflowY: 'auto'},
    arrow: { source: "/sources/ico/faq/arrow.png", width: 16, height: 16 },
    questionContainer: { 
      width: 540, 
      margin: [0, 0, 20, 0], 
      stroke: 2, 
      radius: 5,
      strokeColor: '#DBDBDB',
    },
    questionHeader: {
      width: 540,
      height: 50,
      padding: [0, 30, 0, 20],
      bg: '#DBDBDB',
      cursor: 'pointer',
      radiusTop: 5,
      radiusBottom: 0,
    },
    questionTitle: { 
      fontSize: '1.25rem', 
      fontWeight: 'bold', 
      color: '#333333', 
      margin: [0, 0, 0, 0],
      userSelect: 'none',
    },
    questionContent: { 
      fontSize: '1rem', 
      color: '#333333',
      padding: [15, 20, 15, 20],
      radiusTop: 0,
      radiusBottom: 5,
    },
    checkbox: {
      position: 'absolute',
      opacity: 0,
      cursor: 'pointer',
    }
  },
  museum: {
    window: { width: 1000, height: 800, stroke: 4, bg: '#FFFBE3', radius: 10, overflowHidden: true },
    titleBar: { height: 60, padding: [0, 30, 0, 30], bg: '#FFD992' },
    titleText: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    closeButton: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333' },
    contentArea: { height: 740, padding: [20, 40, 20, 40] },
    sectionTitle: { fontSize: '1.5rem', fontWeight: 'bold', color: '#333333', margin: [0, 0, 0, 0] },
    sectionSubTitle: { fontSize: '0.75rem', fontWeight: 'normal', color: '#333333', margin: [0, 0, 0, 20] },
    sectionContent: { margin: [20, 20, 40, 20] },
    section1: {
      title: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333' },
      book: { width: 300, height: 225, radius: 10 },
      book1: { source: "/sources/img/museum/book/atomic_habits.jpg" },
      book2: { source: "/sources/img/museum/book/deep_work.jpg" },
      bookContent: { fontSize: '1rem', fontWeight: 'normal', color: '#333333', marginSide: 40 },
      book1Frame: { width: 880, height: 225, marginBottom: 40 },
      book2Frame: { width: 880, height: 225 },
    },
    section2: {
      title: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333' },
      picture: { width: 205, height: 205, spacing: 20, borderRadius: 10, backgroundColor: '#DBDBDB' },
      picture1: { source: "/sources/img/museum/tech/ipad_gen_1st.jpg" },
      picture2: { source: "/sources/img/museum/tech/ipad_gen_8th.jpg" },
      picture3: { source: "/sources/img/museum/tech/ipad_air_4.jpg" },
      picture4: { source: "/sources/img/museum/tech/ipad_air_5.jpg" },
      picture5: { source: "/sources/img/museum/tech/acer_nitro_5.jpg" },
      picture6: { source: "/sources/img/museum/tech/attack_shark_x3.jpg" },
      picture7: { source: "/sources/img/museum/tech/za68_pro.jpg" },
      picture8: { source: "/sources/img/museum/tech/moondrop_space_travel.jpg" },
      picture9: { source: "/sources/img/museum/tech/hyperone_with_m575s.jpg" },
      picture10: { source: "/sources/img/museum/tech/logitech_m575s.jpg" },
      picture11: { source: "/sources/img/museum/tech/seiko_watch.jpg" },
      picture12: { source: "/sources/img/museum/tech/asus_vivobook_x509fa.jpg" },
      picture13: { source: "/sources/img/museum/tech/logitech_cordless_trackman_wheel.jpg" },
      picture14: { source: "/sources/img/museum/tech/protoarc_em01_white_rgb-ring.jpg" },
      picture15: { source: "/sources/img/museum/tech/hhkb_pro_hybrid_type-s_snow.jpg" },
      picture16: { source: "/sources/img/museum/tech/legion_pro_5_2023_white.jpg" },
    },
    section3: {
      title: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333' },
    },
    section4: {
      title: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333' },
      game1Frame: { width: 880, height: 225, marginBottom: 40},
      game2Frame: { width: 880, height: 208 },
      game1Pic: { width: 300, height: 225, borderRadius: 10, source: "/sources/img/museum/game/free_fire.jpg" },
      game2Pic: { width: 300, height: 208, borderRadius: 10, source: "/sources/img/museum/game/arena_of_valor.jpg" },
      gameName: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333', margin: [20, 0, 5, 40] },
      gameContent: { fontSize: '1rem', fontWeight: 'normal', color: '#333333', margin: [5, 0, 0, 40] },
    },
    section5: {
      title: { fontSize: '1.25rem', fontWeight: 'bold', color: '#333333' },
    },
  },
};
